apiVersion: helm.hops.ops.com.ai/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: example-env
spec:
  clusterName: example-cluster
  labels:
    team: platform
  namespace: kiali
  values:
    auth:
      strategy: anonymous
